# Generated by Django 3.1.1 on 2020-09-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursenumber', models.CharField(blank=True, max_length=45, null=True)),
                ('coursename', models.CharField(blank=True, max_length=45, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('placeid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('block', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scorelookup',
            fields=[
                ('score', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'scorelookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=45, null=True)),
                ('lname', models.CharField(blank=True, max_length=45, null=True)),
                ('department', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=45, null=True)),
                ('lname', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Courseplace',
            fields=[
                ('courses_courseid', models.OneToOneField(db_column='courses_courseid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='erpApp.courses')),
            ],
            options={
                'db_table': 'courseplace',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studentcourse',
            fields=[
                ('students_studentid', models.OneToOneField(db_column='students_studentid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='erpApp.students')),
            ],
            options={
                'db_table': 'studentcourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('courses_courseid', models.OneToOneField(db_column='courses_courseid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='erpApp.courses')),
            ],
            options={
                'db_table': 'ta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teachercourse',
            fields=[
                ('teachers_teacherid', models.OneToOneField(db_column='teachers_teacherid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='erpApp.teachers')),
            ],
            options={
                'db_table': 'teachercourse',
                'managed': False,
            },
        ),
    ]
