# Generated by Django 3.1.1 on 2020-09-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
